services:
  caddy:
    build:
      context: proxy
      dockerfile: $PWD/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - $PWD/proxy:/etc/caddy
    environment:
      # Provide the CF env fixtures... more are needed!
      - PORT=8080

      # The variables that matter to the app
      - PROXY_USERNAME=user
      - PROXY_PASSWORD=pass
      - PROXY_DENY=translate.google.com
      - PROXY_ALLOW=*.google.com

      # test export_http_proxy.sh
      - PROXY_USERNAME_client=clientuser
      - PROXY_PASSWORD_client=clientpass
