version: "3.7"

services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - PORT=8080
      - USER=user
      - PASS=pass
      # - ALLOWPORT=22
      # - ALLOWPORTS="80 443"
      # - ALLOWHOST="cnn.com"

volumes:
  caddy_data:
  caddy_config: