version: "3.7"

services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - PORT=443
      - ROUTE=egress-proxy.app.internal

volumes:
  caddy_data:
  caddy_config: