---
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  test:
    name: Test that caddy builds + Validate Caddyfile
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build caddy - setup go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: build caddy - get xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - name: build caddy - xcaddy build
        run: >
          xcaddy build
          --with github.com/caddyserver/forwardproxy
          --output proxy/caddy
      - name: validate Caddyfile
        run: make validate
